#include <iostream>
#include <iomanip>
#include <cstdint>
#include <fstream>
#include <ios>
#include "ScalingFunction.h"

using std::cout;
using std::endl;
using std::setw;
using std::ofstream;

int main (int argc, char **argv) {

  if (argc == 0 || ((argc - 1) % 4) != 0) {
    cout << "Usage: " << argv[0] << " type offset base slope [type offset base slope [...]]" << endl;
    return -1;
  }

  int argcBase = 1;
  ScalingFunction::FunctionType type = (ScalingFunction::FunctionType)atoi(argv[argcBase++]);
  uint16_t offset = atoi(argv[argcBase++]);
  uint16_t base = atoi(argv[argcBase++]);
  float slope = atof(argv[argcBase++]);

  ScalingFunction scale(type, offset, base, slope);

  while (argc > argcBase) {
    type = (ScalingFunction::FunctionType)atoi(argv[argcBase++]);
    offset = atoi(argv[argcBase++]);
    base = atoi(argv[argcBase++]);
    slope = atof(argv[argcBase++]);
    scale.addOverlay(type, offset, base, slope);
  }

  for (uint16_t i = 0; i < 4096; i++) {
    cout << setw(5) << i << "; " 
      << scale[i]
      << endl;
  }

  ofstream myfile;
  myfile.open ("SFcli.h", std::ios::out | std::ios::trunc);
  if (myfile) {
    myfile << "// Generated by " << argv[0] << endl;
    myfile << "//   Parameters:" << endl << "//     ";
    for (int i = 1; i < argc; i++) {
      myfile << argv[i] << ", ";
    }
    myfile << endl << " " << endl;
    myfile << "#include <array>" << endl 
      << "#include <cstdint>" << endl 
      << "using std::array;" << endl 
      << endl;
    myfile << "array<uint16_t, 4096> _WOZZMYNAME_ = {" << endl << "  ";
    for (uint16_t i = 0; i < 4096; ++i) {
      myfile << setw(5) << scale[i] << ", ";
      if (i && i % 16 == 15) {
        myfile << endl << "  ";
      }
    }
    myfile << endl << "};" << endl;
  }
  myfile.close();

  return 0;
}