name: Issue Report
description: File a bug report, feature request or idea.
body:
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of FredBoard are you running?
      options:
        - alpha5.1
        - alpha5.1.A
        - alpha5.2
        - alpha5.3
        - "not applicable"
      default: 0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What is the issue?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
