name: Issue Report
description: File a bug report, feature request or idea.
body:
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of FredBOard are you running?
      options:
        - alpha4d
        - none
      default: 0
    validations:
      required: true

